# [[file:~/Workspace/Programming/gosh-rs/qsubmit/qsubmit.note::*cargo][cargo:1]]
[package]
name = "qsubmit"
version = "0.0.1"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]

[dev-dependencies]
# cargo:1 ends here
