[tasks.i]
#command = "env"
script = '''#! /usr/bin/env bash
set -xe
cargo im --offline --root=releases/${CARGO_MAKE_CRATE_VERSION} --no-track --bins --force
upx releases/${CARGO_MAKE_CRATE_VERSION}/bin/*
'''
